# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiverinfo',
            options={'verbose_name': '收件人信息', 'verbose_name_plural': '收件人信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
