# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191107_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
    ]
