# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191104_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_login',
        ),
    ]
