# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191107_1933'),
        ('user', '0003_auto_20191107_1929'),
    ]

    operations = [
    ]
