# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinfo_is_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
