# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='total_amount',
            field=models.IntegerField(verbose_name='订单商品总数'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='订单总价'),
        ),
    ]
