# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191107_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelTable(
            name='ordergoods',
            table='order_goods',
        ),
    ]
