# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191107_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='name',
            field=models.CharField(max_length=180, verbose_name='商品名称'),
        ),
    ]
