# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191109_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='total_amount',
            new_name='total_count',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='total_money',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='name',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods_id',
            field=models.IntegerField(default=0, verbose_name='商品名称'),
        ),
    ]
