# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191110_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='name',
            field=models.CharField(default='', max_length=180, verbose_name='商品名称'),
        ),
    ]
