# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191111_0901'),
        ('order', '0006_auto_20191111_0947'),
    ]

    operations = [
    ]
