# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='分类名字')),
                ('description', models.TextField(verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '商品分类信息',
                'verbose_name_plural': '商品分类信息',
                'db_table': 'commodity_classify',
            },
        ),
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=180, verbose_name='商品名')),
                ('shelves', models.BooleanField(default=True, verbose_name='是否在售')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('images', models.ImageField(blank=True, null=True, upload_to='commodity/', verbose_name='商品图片')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityClassify', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'commodity_info',
            },
        ),
    ]
