# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-02 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classify',
            new_name='CommodityClassify',
        ),
        migrations.RenameModel(
            old_name='Commodity',
            new_name='CommodityInfo',
        ),
        migrations.AlterModelTable(
            name='commodityclassify',
            table='commodity_classify',
        ),
        migrations.AlterModelTable(
            name='commodityinfo',
            table='commodity_info',
        ),
    ]
