# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfo',
            name='storage',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
    ]
