# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_commodityinfo_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfo',
            name='description',
            field=models.TextField(default='', verbose_name='商品描述'),
        ),
    ]
