# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20191102_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityclassify',
            options={'verbose_name': '商品分类信息', 'verbose_name_plural': '商品分类信息'},
        ),
        migrations.AlterModelOptions(
            name='commodityinfo',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
    ]
