# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20191110_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityclassify',
            name='description',
            field=models.TextField(default='', verbose_name='分类描述'),
        ),
    ]
